print ("Hello world")
print ("I am PP POng")
print ("I am from Nakhonphanom Thailand")
print ("I am a lecturer")
print ("My office is MIT-NNakhonphanom University")
print ("ฉันเป็นคนไทย คนไทยแปลว่าอิสระ")
